version: '2'
 
services:
    couchbase:
        image: couchbase
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 8094:8094
        environment:
            - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
            - COUCHBASE_ADMINISTRATOR_PASSWORD=password
            - COUCHBASE_BUCKET=Transactions
            - COUCHBASE_BUCKET_PASSWORD=
        
    payment-gateway:
        build: .
        restart: always
        ports:
          - 5000:80
        environment:
          - Couchbase:Servers:0=http://$COMPUTERNAME:8091/
        depends_on:
          - couchbase